#!/bin/bash

## Atualizando o repositório ##

sudo apt update

## VSCode Extensions Milton Rodrigues ##

code --install-extension 2gua.rainbow-brackets
code --install-extension anseki.vscode-color
code --install-extension CoenraadS.bracket-pair-colorizer-2
code --install-extension dbaeumer.vscode-eslint
code --install-extension esbenp.prettier-vscode
code --install-extension jpoissonnier.vscode-styled-components
code --install-extension kamikillerto.vscode-colorize
code --install-extension maykbrito.theme-launchbase
code --install-extension naumovs.color-highlight
code --install-extension PKief.material-icon-theme
code --install-extension pranaygp.vscode-css-peek
code --install-extension ritwickdey.LiveServer
code --install-extension searKing.preview-vscode
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension vincaslt.highlight-matching-tag
code --install-extension xshrim.txt-syntax

