#!/bin/bash

## Atualizando o repositório ##

sudo apt update

## VSCode Extensions Milton Rodrigues ##

code --install-extension 2gua.rainbow-brackets
code --install-extension anseki.vscode-color
code --install-extension CoenraadS.bracket-pair-colorizer-2
code --install-extension dbaeumer.vscode-eslint
code --install-extension eamodio.gitlens
code --install-extension esbenp.prettier-vscode
code --install-extension formulahendry.code-runner
code --install-extension GitHub.github-vscode-theme
code --install-extension jpoissonnier.vscode-styled-components
code --install-extension kamikillerto.vscode-colorize
code --install-extension mhutchie.git-graph
code --install-extension Miltonr87.dark-walker
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension ms-vsliveshare.vsliveshare-audio
code --install-extension ms-vsliveshare.vsliveshare-pack
code --install-extension Nixon.env-cmd-file-syntax
code --install-extension rangav.vscode-thunder-client
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension vincaslt.highlight-matching-tag
code --install-extension vscode-icons-team.vscode-icons
code --install-extension xshrim.txt-syntax
