#!/bin/bash

## Atualizando o repositório ##

sudo apt update

## VSCode Extensions Milton Rodrigues ##

code --install-extension 2gua.rainbow-brackets
code --install-extension anseki.vscode-color
code --install-extension christian-kohler.npm-intellisense
code --install-extension christian-kohler.path-intellisense
code --install-extension CoenraadS.bracket-pair-colorizer
code --install-extension CoenraadS.bracket-pair-colorizer-2
code --install-extension dbaeumer.vscode-eslint
code --install-extension eamodio.gitlens
code --install-extension esbenp.prettier-vscode
code --install-extension formulahendry.code-runner
code --install-extension GraphQL.vscode-graphql
code --install-extension jpoissonnier.vscode-styled-components
code --install-extension kamikillerto.vscode-colorize
code --install-extension maykbrito.theme-launchbase
code --install-extension mgmcdermott.vscode-language-babel
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension PKief.material-icon-theme
code --install-extension pranaygp.vscode-css-peek
code --install-extension ritwickdey.LiveServer
code --install-extension ryu1kn.text-marker
code --install-extension searKing.preview-vscode
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension vincaslt.highlight-matching-tag
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension xshrim.txt-syntax
code --install-extension yzhang.markdown-all-in-one
code --install-extension Zignd.html-css-class-completion
