#!/bin/bash

## Começando meu Shell Script! ##

sudo rm var lib dpkg lock-frontend ; sudo rm/var/cache/apt/archives/lock; 

## Atualizando o repositório ##

sudo apt update

## Download de aplicativos externos: ##

mkdir /home/$USER/Downloads/programas

cd /home/$USER/Downloads/programas

## Stacer Gerenciador de Tarefas ##

wget -c https://github.com/oguzhaninan/Stacer/releases/download/v1.1.0/stacer_1.1.0_amd64.deb

## Google Chrome ##

wget -c https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

## VSCode Microsoft Professional ##

wget -c https://go.microsoft.com/fwlink/?LinkID=760868

## GitHub Desktop Linux

wget -qO - https://packagecloud.io/shiftkey/desktop/gpgkey | sudo tee /etc/apt/trusted.gpg.d/shiftkey-desktop.asc > /dev/null
sudo sh -c 'echo "deb [arch=amd64] https://packagecloud.io/shiftkey/desktop/any/ any main" > /etc/apt/sources.list.d/packagecloud-shiftky-desktop.list'
sudo apt-get update
sudo apt install github-desktop

## OnlyOffice Desktop Edition ##

wget -c  https://download.onlyoffice.com/install/desktop/editors/linux/onlyoffice-desktopeditors_amd64.deb?_ga=2.57419820.764533964.1595236576-1157782750.1587541027


sudo dpkg -i *.deb


## Brave Browser ##

sudo apt install apt-transport-https curl

curl -s https://brave-browser-apt-release.s3.brave.com/brave-core.asc | sudo apt-key --keyring /etc/apt/trusted.gpg.d/brave-browser-release.gpg add -

echo "deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main" | sudo tee /etc/apt/sources.list.d/brave-browser-release.list

sudo apt install brave-browser


## Atualizando Essenciais do Sistema ##

## Codecs essenciais ##

sudo apt install mint-meta-codecs -y

## Fontes do Windows ##

sudo apt-get install ttf-mscorefonts-installer -y

## Instalado o Snap Store ##

sudo rm /etc/apt/preferences.d/nosnap.pref

sudo apt install snapd -y

## Steam ##

sudo apt install steam-installer steam-devices steam:i386 -y

## Lutris e Wine ##

sudo add-apt-repository ppa:lutris-team/lutris -y

sudo apt upgdate

sudo apt install lutris -y

sudo dpkg --add-architecture i386

wget -nc https://dl.winehq.org/wine-builds/winehq.key

sudo apt-key add winehq.key

sudo apt update

sudo apt install --install-recomends winehq-stable -y

sudo apt install libgnutls30:i386 libldap-2.4-2:i386 libgpg-error0:i386 libsqlite3-0:i386 -y

sudo apt update && sudo apt dist-upgrade

echo "Instalação concluída com sucesso"











