#!/bin/bash

## Starting my Shell Script! ##

sudo rm var lib dpkg lock-frontend ; sudo rm/var/cache/apt/archives/lock; 

## Updating the repository ##

sudo apt update

## Removing Redshift (don't worry!) ##

sudo apt remove redshift -y

## Downloading external applications ##

mkdir /home/$USER/Downloads/programas

cd /home/$USER/Downloads/programas

## Stacer Task Manager ##

wget -c https://github.com/oguzhaninan/Stacer/releases/download/v1.1.0/stacer_1.1.0_amd64.deb

## Flux to replace RedShift (for LINUX MINT) ##

wget -c https://launchpad.net/~nathan-renniewaldock/+archive/ubuntu/flux/+files/fluxgui_1.2.0~pre~20190501-g0548b6f-1~bionic_all.deb

## Google Chrome ##

wget -c https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

## VSCode Microsoft Professional ##

wget -c https://go.microsoft.com/fwlink/?LinkID=760868

## OnlyOffice Desktop Edition ##

wget -c  https://download.onlyoffice.com/install/desktop/editors/linux/onlyoffice-desktopeditors_amd64.deb?_ga=2.57419820.764533964.1595236576-1157782750.1587541027


sudo dpkg -i *.deb

## GitHub Desktop Linux

wget -qO - https://packagecloud.io/shiftkey/desktop/gpgkey | sudo tee /etc/apt/trusted.gpg.d/shiftkey-desktop.asc > /dev/null
sudo sh -c 'echo "deb [arch=amd64] https://packagecloud.io/shiftkey/desktop/any/ any main" > /etc/apt/sources.list.d/packagecloud-shiftky-desktop.list'
sudo apt install github-desktop

## Brave Browser ##

sudo apt install apt-transport-https curl

curl -s https://brave-browser-apt-release.s3.brave.com/brave-core.asc | sudo apt-key --keyring /etc/apt/trusted.gpg.d/brave-browser-release.gpg add -

echo "deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main" | sudo tee /etc/apt/sources.list.d/brave-browser-release.list

sudo apt install brave-browser


## Updating System Essentials ##

## Codecs essentials ##

sudo apt install mint-meta-codecs -y

## Windows original fonts ##

sudo apt-get install ttf-mscorefonts-installer -y

## Snap Store ##

sudo rm /etc/apt/preferences.d/nosnap.pref

sudo apt install snapd -y

## Steam ##

sudo apt install steam-installer steam-devices steam:i386 -y

## Lutris and Wine ##

sudo add-apt-repository ppa:lutris-team/lutris -y

sudo apt install lutris -y

wget -nc https://dl.winehq.org/wine-builds/winehq.key

sudo apt-key add winehq.key

sudo apt update

sudo apt install --install-recomends winehq-stable -y

sudo apt update && sudo apt dist-upgrade

echo "Installation completed successfully"











